openapi: "3.0.0"
info:
  version: 0.0.1
  title: CUE API Docment
servers:
  - url: https://dev.api.cue.colere.inc
paths:
  $ref: "./paths/index.yml"

components:
  schemas:
    $ref: "./schemas/index.yml"
