openapi: 3.0.0
info:
  title: アクション履歴
  description: アクション履歴
  version: "0.0.1"
paths:
  /accounts/{accounts_id}/actions?offset=10&limit=10&order=asc:
    get:
      tags:
        - アクション履歴取得
      description: 指定のアカウントに対するアクション履歴一覧を取得する。
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            example: application/json
        - in: header
          name: X-Request-ID
          required: false
          schema:
            type: string
        - in: header
          name: "Authorization: Bearer"
          required: true
          description: アクセストークン
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiJ9
        - in: path
          name: accounts_id
          schema:
            type: string
          required: true
          description: accountのID
        - in: query
          name: offset
          schema:
            type: integer
          description: 何件目から取得するか
        - in: query
          name: limit
          schema:
            type: integer
          description: 何件取得するか
        - in: query
          name: order
          schema:
            type: string
          description: 昇順(asc) or 降順(desc)
      requestBody:
        content:
          application/json:
            schema:
              type: object

      responses:
        "200":
          description: 取得成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                  $ref: '../schemas/action.yml'
        "400":
          description: リクエストに問題あり
        "401":
          description: Authorizationヘッダーに問題あり
        "403":
          description: アクセス権がない
        "500":
          description: サーバーの一時的なエラー

  /accounts/{accounts_id}/actions/{actions_id}:
    put:
      tags:
        - アクション履歴更新
      description: 指定のアカウントに対する指定のアクション情報を更新する。
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            example: application/json
        - in: header
          name: X-Request-ID
          required: false
          schema:
            type: string
        - in: header
          name: "Authorization: Bearer"
          required: true
          description: アクセストークン
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiJ9
        - in: path
          name: accounts_id
          schema:
            type: string
          required: true
          description: accountのID
        - in: path
          name: actions_id
          schema:
            type: string
          required: true
          description: actionのID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                action_date:
                  type: string
                  description: 実行した日付
                  example: 2022/01/02

      responses:
        "200":
          description: 更新成功
          content:
            application/json:
              schema:
                type: object
                properties:
                $ref: '../schemas/action.yml'
        "400":
          description: リクエストに問題あり
        "401":
          description: Authorizationヘッダーに問題あり
        "403":
          description: アクセス権がない
        "500":
          description: サーバーの一時的なエラー
