openapi: 3.0.0
info:
  title: フィードバック
  description: アクションに対するフィードバック
  version: "0.0.1"
paths:
  /actions/{actions_id}/feedbacks:
    get:
      tags:
        - フィードバック取得
      description: 特定のアクションに対するフィードバック一覧を取得する。
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            example: application/json
        - in: header
          name: X-Request-ID
          required: false
          schema:
            type: string
        - in: header
          name: "Authorization: Bearer"
          required: true
          description: アクセストークン
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiJ9
      requestBody:
        content:
          application/json:
            schema:
              type: object

      responses:
        "200":
          description: 取得成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                  $ref: '../schemas/feedback.yml'
        "400":
          description: リクエストに問題あり
        "401":
          description: Authorizationヘッダーに問題あり
        "403":
          description: アクセス権がない
        "500":
          description: サーバーの一時的なエラー

    post:
      tags:
        - フィードバック作成
      description: 特定のアクションに対するフィードバックを作成する。
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            example: application/json
        - in: header
          name: X-Request-ID
          required: false
          schema:
            type: string
        - in: header
          name: "Authorization: Bearer"
          required: true
          description: アクセストークン
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiJ9
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                action_id:
                  type: string
                  description: actionID
                  example: 0a1b2c3d4e5f6g7
                feedback_id:
                  type: string
                  description: feedbackID
                  example: 0a1b2c3d4e5f6g7
                account_id:
                  type: string
                  description: feedbackしたアカウントID
                  example: 0a1b2c3d4e5f6g7
                contents:
                  type: string
                  description: feedback内容
                  example: よかったです。
              required:
                - action_id
                - feedback_id
                - contents

      responses:
        "200":
          description: 作成成功
          content:
            application/json:
              schema:
                type: object
                properties:
                $ref: '../schemas/feedback.yml'
        "400":
          description: リクエストに問題あり
        "401":
          description: Authorizationヘッダーに問題あり
        "403":
          description: アクセス権がない
        "500":
          description: サーバーの一時的なエラー

  /actions/{actions_id}/feedbacks/{feedbacks_id}:
    put:
      tags:
        - フィードバック更新
      description: 特定のアクションに対するフィードバックを更新する。
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            example: application/json
        - in: header
          name: X-Request-ID
          required: false
          schema:
            type: string
        - in: header
          name: "Authorization: Bearer"
          required: true
          description: アクセストークン
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiJ9
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: feedbackのID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                contents:
                  type: string
                  description: feedback内容
                  example: よかったです。

      responses:
        "200":
          description: 更新成功
          content:
            application/json:
              schema:
                type: object
                properties:
                $ref: '../schemas/feedback.yml'
        "400":
          description: リクエストに問題あり
        "401":
          description: Authorizationヘッダーに問題あり
        "403":
          description: アクセス権がない
        "500":
          description: サーバーの一時的なエラー

    delete:
      tags:
        - フィードバック削除
      description: 特定のアクションに対するフィードバックを削除する。
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            example: application/json
        - in: header
          name: X-Request-ID
          required: false
          schema:
            type: string
        - in: header
          name: "Authorization: Bearer"
          required: true
          description: アクセストークン
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiJ9
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: feedbackのID
      requestBody:
        content:
          application/json:
            schema:
              type: object

      responses:
        "204":
          description: 削除成功
        "400":
          description: リクエストに問題あり
        "401":
          description: Authorizationヘッダーに問題あり
        "403":
          description: アクセス権がない
        "500":
          description: サーバーの一時的なエラー
