openapi: 3.0.0
info:
  title: アカウント
  description: アカウント単体
  version: "0.0.1"
paths:
  /account:
    get:
      tags:
        - アカウント情報取得
      description: 現在ログインしているアカウントの情報を取得する。
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            example: application/json
        - in: header
          name: X-Request-ID
          required: false
          schema:
            type: string
        - in: header
          name: "Authorization: Bearer"
          required: true
          description: アクセストークン
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiJ9
      requestBody:
        content:
          application/json:
            schema:
              type: object

      responses:
        "200":
          description: 取得成功
          content:
            application/json:
              schema:
                type: object
                properties:
                $ref: '#/components/schemas/Account'
        "400":
          description: リクエストに問題あり
        "401":
          description: Authorizationヘッダーに問題あり
        "403":
          description: アクセス権がない
        "500":
          description: サーバーの一時的なエラー

    post:
      tags:
        - アカウント作成
      description: 上司 or 部下からの招待で作成する場合(with_account_relation, id)は AccountRelation、InitialRelationship、RelationshipPointも作成される。
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            example: application/json
        - in: header
          name: X-Request-ID
          required: false
          schema:
            type: string
        - in: header
          name: "Authorization: Bearer"
          required: true
          description: アクセストークン
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiJ9
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                last_name:
                  type: string
                  description: 名
                  example: 太郎
                first_name:
                  type: string
                  description: 姓
                  example: 山田
                email:
                  type: string
                  description: メールアドレス
                  example: example@colere.inc
                icon:
                  type: string
                  description: アイコンのURL
                  example: icon@pmf.com
                gender:
                  type: string
                  description: 性
                  example: 男
              required:
                - email

      responses:
        "200":
          description: 作成成功
          content:
            application/json:
              schema:
                type: object
                properties:
                $ref: '#/components/schemas/Account'
        "400":
          description: リクエストに問題あり
        "401":
          description: Authorizationヘッダーに問題あり
        "403":
          description: アクセス権がない
        "500":
          description: サーバーの一時的なエラー

    put:
      tags:
        - アカウント情報更新
      description: アカウント情報を更新する。
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            example: application/json
        - in: header
          name: X-Request-ID
          required: false
          schema:
            type: string
        - in: header
          name: "Authorization: Bearer"
          required: true
          description: アクセストークン
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiJ9
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                last_name:
                  type: string
                  description: 名
                  example: 太郎
                first_name:
                  type: string
                  description: 姓
                  example: 山田
                email:
                  type: string
                  description: メールアドレス
                  example: example@colere.inc
                icon:
                  type: string
                  description: アイコンのURL
                  example: icon@pmf.com
                gender:
                  type: string
                  description: 性
                  example: 男

      responses:
        "200":
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        "400":
          description: リクエストに問題あり
        "401":
          description: Authorizationヘッダーに問題あり
        "403":
          description: アクセス権がない
        "500":
          description: サーバーの一時的なエラー
