openapi: 3.0.0
info:
  title: ポイント変化通知
  description: Home画面のポイント変化通知用
  version: "0.0.1"
paths:
  /changable_notifications:
    get:
      tags:
        - ポイント変化通知取得
      description: ログインしているアカウントのポイント変化通知一覧を取得する。
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            example: application/json
        - in: header
          name: X-Request-ID
          required: false
          schema:
            type: string
        - in: header
          name: "Authorization: Bearer"
          required: true
          description: アクセストークン
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiJ9
      requestBody:
        content:
          application/json:
            schema:
              type: object

      responses:
        "200":
          description: 取得成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                  $ref: '#/components/schemas/ChangableNotification'
        "400":
          description: リクエストに問題あり
        "401":
          description: Authorizationヘッダーに問題あり
        "403":
          description: アクセス権がない
        "500":
          description: サーバーの一時的なエラー

  /changable_notifications/{changable_notifications_id}:
    put:
      tags:
        - ポイント変化通知更新
      description: ログインしているアカウントのポイント変化通知一覧を更新する。
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            example: application/json
        - in: header
          name: X-Request-ID
          required: false
          schema:
            type: string
        - in: header
          name: "Authorization: Bearer"
          required: true
          description: アクセストークン
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiJ9
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: changable_notificationのID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                is_read:
                  type: boolean
                  description: 既読したかどうか
                  example: true

      responses:
        "200":
          description: 更新成功
          content:
            application/json:
              schema:
                type: object
                properties:
                $ref: '#/components/schemas/ChangableNotification'
        "400":
          description: リクエストに問題あり
        "401":
          description: Authorizationヘッダーに問題あり
        "403":
          description: アクセス権がない
        "500":
          description: サーバーの一時的なエラー
