openapi: 3.0.0
info:
  title: 関係性レベルポイント
  description: 関係性レベルポイント
  version: "0.0.1"
paths:
  /relationship_points:
    get:
      tags:
        - 関係性レベルポイント取得
      description: 現在ログインしているアカウントに関連する関係性レベルのポイントをすべて取得する。<br>account_relationごとに最新の日付のもののみ取得する。
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            example: application/json
        - in: header
          name: X-Request-ID
          required: false
          schema:
            type: string
        - in: header
          name: "Authorization: Bearer"
          required: true
          description: アクセストークン
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiJ9
      requestBody:
        content:
          application/json:
            schema:
              type: object

      responses:
        "200":
          description: 取得成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                  $ref: '../schemas/relationsip_point.yml'
        "400":
          description: リクエストに問題あり
        "401":
          description: Authorizationヘッダーに問題あり
        "403":
          description: アクセス権がない
        "500":
          description: サーバーの一時的なエラー
