openapi: 3.0.0
info:
  title: 指定した関連性に関する全ての関係性レベルポイント
  description: 指定した関連性に関する全ての関係性レベルポイント
  version: "0.0.1"
paths:
  /account_relations/{id}/relationship_points?offset=10&limit=10&order=asc:
    get:
      tags:
        - 関係性レベルポイント取得
      description: 指定のaccount_relationの関係性レベルのポイントをすべてを取得する。
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            example: application/json
        - in: header
          name: X-Request-ID
          required: false
          schema:
            type: string
        - in: header
          name: "Authorization: Bearer"
          required: true
          description: アクセストークン
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiJ9
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: relationship_pointのID
        - in: query
          name: offset
          schema:
            type: integer
          description: 何件目から取得するか
        - in: query
          name: limit
          schema:
            type: integer
          description: 何件取得するか
        - in: query
          name: order
          schema:
            type: string
          description: 昇順(asc) or 降順(desc)
      requestBody:
        content:
          application/json:
            schema:
              type: object

      responses:
        "200":
          description: 取得成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                  $ref: '../../schemas/relationship_point.yml'
        "400":
          description: リクエストに問題あり
        "401":
          description: Authorizationヘッダーに問題あり
        "403":
          description: アクセス権がない
        "500":
          description: サーバーの一時的なエラー
