openapi: 3.0.0
info:
  title: アカウント情報取得(Admin)
  description: 管理用のアカウント情報取得(Admin)
  version: "0.0.1"
paths:
  /accounts:
    get:
      tags:
        - アカウント情報取得
      description: アカウントをすべて取得する。
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            example: application/json
        - in: header
          name: X-Request-ID
          required: false
          schema:
            type: string
        - in: header
          name: "Authorization: Bearer"
          required: true
          description: アクセストークン
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiJ9
      requestBody:
        content:
          application/json:
            schema:
              type: object

      responses:
        "200":
          description: 取得成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                  $ref: '#/components/schemas/Account'
        "400":
          description: リクエストに問題あり
        "401":
          description: Authorizationヘッダーに問題あり
        "403":
          description: アクセス権がない
        "500":
          description: サーバーの一時的なエラー


components:
  schemas:
    Account:
      type: object
      description: アカウント
      properties:
        id:
          type: string
          description: ID
          example: 0a1b2c3d4e5f6g7
          minLength: 15
          maxLength: 15
          pattern: '^[0-9a-z]$'
        last_name:
          type: string
          description: 名
          example: 太郎
        first_name:
          type: string
          description: 姓
          example: 山田
        email:
          type: string
          description: メールアドレス
          example: example@colere.inc
        icon:
          type: string
          description: アイコンのURL
          example: icon@pmf.com
        gender:
          type: string
          description: 性
          example: 男
      required:
        - id
