openapi: 3.0.0
info:
  title: 外部連携アプリ
  description: 外部連携アプリ管理用
  version: "0.0.1"
paths:
  /changable_notifications:
    get:
      tags:
        - 外部連携アプリ取得
      description: ログインしているアカウントの連携した外部アプリ情報をすべて取得する。
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            example: application/json
        - in: header
          name: X-Request-ID
          required: false
          schema:
            type: string
        - in: header
          name: "Authorization: Bearer"
          required: true
          description: アクセストークン
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiJ9
      requestBody:
        content:
          application/json:
            schema:
              type: object

      responses:
        "200":
          description: 取得成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                  $ref: '#/components/schemas/ExternlApp'
        "400":
          description: リクエストに問題あり
        "401":
          description: Authorizationヘッダーに問題あり
        "403":
          description: アクセス権がない
        "500":
          description: サーバーの一時的なエラー

  /changable_notifications/{changable_notifications_id}:
    put:
      tags:
        - 外部連携アプリ取得
      description: 連携した外部アプリ情報を更新する。
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            example: application/json
        - in: header
          name: X-Request-ID
          required: false
          schema:
            type: string
        - in: header
          name: "Authorization: Bearer"
          required: true
          description: アクセストークン
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiJ9
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: external_appのID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: 外部アプリへの遷移先URL(Custom URL Scheme含む)
                  example: instagram://app

      responses:
        "200":
          description: 更新成功
          content:
            application/json:
              schema:
                type: object
                properties:
                $ref: '#/components/schemas/ExternlApp'
        "400":
          description: リクエストに問題あり
        "401":
          description: Authorizationヘッダーに問題あり
        "403":
          description: アクセス権がない
        "500":
          description: サーバーの一時的なエラー


components:
  schemas:
    ExternlApp:
      type: object
      description: ポイント変更通知
      properties:
        id:
          type: string
          description: ID
          example: 0a1b2c3d4e5f6g7
        account_id:
          type: string
          description: 対象のアカウントID
          example: 0a1b2c3d4e5f6g7
        name:
          type: string
          description: アプリの名前
          example: Microsoft Teams
        url:
          type: string
          description: 外部アプリへの遷移先URL(Custom URL Scheme含む)
          example: instagram://app
