openapi: 3.0.0
info:
  title: アクセストークン
  description: アクセストークン
  version: "0.0.1"
paths:
  /auth/token:
    post:
      tags:
        - アクセストークン新規発行
      description: アクセストークンを発行する。
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            example: application/json
        - in: header
          name: X-Request-ID
          required: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object

      responses:
        "200":
          description: 発行成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: アクセストークン
                    example: eyJhbGciOiJIUzI1NiJ9
